// Mocks generated by Mockito 5.4.6 from annotations
// in aorlando/test/feature/home/home_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:aorlando/core/utils/errors/failure_entity.dart' as _i6;
import 'package:aorlando/feature/home/domain/entities/contacts_entity.dart'
    as _i9;
import 'package:aorlando/feature/home/domain/entities/cv_entity.dart' as _i7;
import 'package:aorlando/feature/home/domain/entities/driving_license_entity.dart'
    as _i14;
import 'package:aorlando/feature/home/domain/entities/educations_entity.dart'
    as _i12;
import 'package:aorlando/feature/home/domain/entities/languages_entity.dart'
    as _i13;
import 'package:aorlando/feature/home/domain/entities/skills_and_competences_entity.dart'
    as _i15;
import 'package:aorlando/feature/home/domain/entities/social_link_entity.dart'
    as _i10;
import 'package:aorlando/feature/home/domain/entities/work_experiences_entity.dart'
    as _i11;
import 'package:aorlando/feature/home/domain/repositories/home_repository.dart'
    as _i2;
import 'package:aorlando/feature/home/domain/use_cases/get_cv_use_case.dart'
    as _i4;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHomeRepository_0 extends _i1.SmartFake
    implements _i2.HomeRepository {
  _FakeHomeRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetCvUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCvUseCase extends _i1.Mock implements _i4.GetCvUseCase {
  @override
  _i2.HomeRepository get homeRepository =>
      (super.noSuchMethod(
            Invocation.getter(#homeRepository),
            returnValue: _FakeHomeRepository_0(
              this,
              Invocation.getter(#homeRepository),
            ),
            returnValueForMissingStub: _FakeHomeRepository_0(
              this,
              Invocation.getter(#homeRepository),
            ),
          )
          as _i2.HomeRepository);

  @override
  _i5.Future<_i3.Either<_i6.FailureEntity, _i7.CvEntity>> call(
    String? assetPath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [assetPath]),
            returnValue:
                _i5.Future<_i3.Either<_i6.FailureEntity, _i7.CvEntity>>.value(
                  _FakeEither_1<_i6.FailureEntity, _i7.CvEntity>(
                    this,
                    Invocation.method(#call, [assetPath]),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i3.Either<_i6.FailureEntity, _i7.CvEntity>>.value(
                  _FakeEither_1<_i6.FailureEntity, _i7.CvEntity>(
                    this,
                    Invocation.method(#call, [assetPath]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.FailureEntity, _i7.CvEntity>>);
}

/// A class which mocks [CvEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockCvEntity extends _i1.Mock implements _i7.CvEntity {
  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#name)),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  String get surname =>
      (super.noSuchMethod(
            Invocation.getter(#surname),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#surname),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#surname),
            ),
          )
          as String);

  @override
  String get role =>
      (super.noSuchMethod(
            Invocation.getter(#role),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#role)),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#role),
            ),
          )
          as String);

  @override
  String get email =>
      (super.noSuchMethod(
            Invocation.getter(#email),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#email),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#email),
            ),
          )
          as String);

  @override
  String get website =>
      (super.noSuchMethod(
            Invocation.getter(#website),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#website),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#website),
            ),
          )
          as String);

  @override
  String get docUrl =>
      (super.noSuchMethod(
            Invocation.getter(#docUrl),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#docUrl),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#docUrl),
            ),
          )
          as String);

  @override
  String get city =>
      (super.noSuchMethod(
            Invocation.getter(#city),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#city)),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#city),
            ),
          )
          as String);

  @override
  String get birthDate =>
      (super.noSuchMethod(
            Invocation.getter(#birthDate),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#birthDate),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#birthDate),
            ),
          )
          as String);

  @override
  String get description =>
      (super.noSuchMethod(
            Invocation.getter(#description),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#description),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#description),
            ),
          )
          as String);

  @override
  String get privacy =>
      (super.noSuchMethod(
            Invocation.getter(#privacy),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#privacy),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#privacy),
            ),
          )
          as String);

  @override
  List<_i9.ContactsEntity> get contactsEntityList =>
      (super.noSuchMethod(
            Invocation.getter(#contactsEntityList),
            returnValue: <_i9.ContactsEntity>[],
            returnValueForMissingStub: <_i9.ContactsEntity>[],
          )
          as List<_i9.ContactsEntity>);

  @override
  List<_i10.SocialLinkEntity> get socialLinkEntityList =>
      (super.noSuchMethod(
            Invocation.getter(#socialLinkEntityList),
            returnValue: <_i10.SocialLinkEntity>[],
            returnValueForMissingStub: <_i10.SocialLinkEntity>[],
          )
          as List<_i10.SocialLinkEntity>);

  @override
  List<_i11.WorkExperiencesEntity> get workExperiencesEntityList =>
      (super.noSuchMethod(
            Invocation.getter(#workExperiencesEntityList),
            returnValue: <_i11.WorkExperiencesEntity>[],
            returnValueForMissingStub: <_i11.WorkExperiencesEntity>[],
          )
          as List<_i11.WorkExperiencesEntity>);

  @override
  List<_i12.EducationsEntity> get educationsEntityList =>
      (super.noSuchMethod(
            Invocation.getter(#educationsEntityList),
            returnValue: <_i12.EducationsEntity>[],
            returnValueForMissingStub: <_i12.EducationsEntity>[],
          )
          as List<_i12.EducationsEntity>);

  @override
  List<_i13.LanguagesEntity> get languagesEntityList =>
      (super.noSuchMethod(
            Invocation.getter(#languagesEntityList),
            returnValue: <_i13.LanguagesEntity>[],
            returnValueForMissingStub: <_i13.LanguagesEntity>[],
          )
          as List<_i13.LanguagesEntity>);

  @override
  List<_i14.DrivingLicenseEntity> get drivingLicenseEntityList =>
      (super.noSuchMethod(
            Invocation.getter(#drivingLicenseEntityList),
            returnValue: <_i14.DrivingLicenseEntity>[],
            returnValueForMissingStub: <_i14.DrivingLicenseEntity>[],
          )
          as List<_i14.DrivingLicenseEntity>);

  @override
  List<_i15.SkillsAndCompetencesEntity> get skillsAndCompetencesEntityList =>
      (super.noSuchMethod(
            Invocation.getter(#skillsAndCompetencesEntityList),
            returnValue: <_i15.SkillsAndCompetencesEntity>[],
            returnValueForMissingStub: <_i15.SkillsAndCompetencesEntity>[],
          )
          as List<_i15.SkillsAndCompetencesEntity>);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
