// Mocks generated by Mockito 5.4.4 from annotations
// in aorlando/test/feature/home/home_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:aorlando/core/data/requests/base_local_request.dart' as _i4;
import 'package:aorlando/core/domain/data_sources/local/local_data_source.dart'
    as _i2;
import 'package:aorlando/feature/home/domain/entities/contacts_entity.dart'
    as _i7;
import 'package:aorlando/feature/home/domain/entities/cv_entity.dart' as _i5;
import 'package:aorlando/feature/home/domain/entities/driving_license_entity.dart'
    as _i12;
import 'package:aorlando/feature/home/domain/entities/educations_entity.dart'
    as _i10;
import 'package:aorlando/feature/home/domain/entities/languages_entity.dart'
    as _i11;
import 'package:aorlando/feature/home/domain/entities/skills_and_competences_entity.dart'
    as _i13;
import 'package:aorlando/feature/home/domain/entities/social_link_entity.dart'
    as _i8;
import 'package:aorlando/feature/home/domain/entities/work_experiences_entity.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDataSource extends _i1.Mock implements _i2.LocalDataSource {
  @override
  _i3.Future<T?> retrieveData<T>(_i4.BaseLocalRequest<dynamic>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #retrieveData,
          [request],
        ),
        returnValue: _i3.Future<T?>.value(),
        returnValueForMissingStub: _i3.Future<T?>.value(),
      ) as _i3.Future<T?>);

  @override
  _i3.Future<void> saveData(_i4.BaseLocalRequest<dynamic>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveData,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearData(_i4.BaseLocalRequest<dynamic>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearData,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [CvEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockCvEntity extends _i1.Mock implements _i5.CvEntity {
  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  String get surname => (super.noSuchMethod(
        Invocation.getter(#surname),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#surname),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#surname),
        ),
      ) as String);

  @override
  String get role => (super.noSuchMethod(
        Invocation.getter(#role),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#role),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#role),
        ),
      ) as String);

  @override
  String get email => (super.noSuchMethod(
        Invocation.getter(#email),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#email),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#email),
        ),
      ) as String);

  @override
  String get website => (super.noSuchMethod(
        Invocation.getter(#website),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#website),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#website),
        ),
      ) as String);

  @override
  String get docUrl => (super.noSuchMethod(
        Invocation.getter(#docUrl),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#docUrl),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#docUrl),
        ),
      ) as String);

  @override
  String get city => (super.noSuchMethod(
        Invocation.getter(#city),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#city),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#city),
        ),
      ) as String);

  @override
  String get birthDate => (super.noSuchMethod(
        Invocation.getter(#birthDate),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#birthDate),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#birthDate),
        ),
      ) as String);

  @override
  String get description => (super.noSuchMethod(
        Invocation.getter(#description),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#description),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#description),
        ),
      ) as String);

  @override
  String get privacy => (super.noSuchMethod(
        Invocation.getter(#privacy),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#privacy),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#privacy),
        ),
      ) as String);

  @override
  List<_i7.ContactsEntity> get contactsEntityList => (super.noSuchMethod(
        Invocation.getter(#contactsEntityList),
        returnValue: <_i7.ContactsEntity>[],
        returnValueForMissingStub: <_i7.ContactsEntity>[],
      ) as List<_i7.ContactsEntity>);

  @override
  List<_i8.SocialLinkEntity> get socialLinkEntityList => (super.noSuchMethod(
        Invocation.getter(#socialLinkEntityList),
        returnValue: <_i8.SocialLinkEntity>[],
        returnValueForMissingStub: <_i8.SocialLinkEntity>[],
      ) as List<_i8.SocialLinkEntity>);

  @override
  List<_i9.WorkExperiencesEntity> get workExperiencesEntityList =>
      (super.noSuchMethod(
        Invocation.getter(#workExperiencesEntityList),
        returnValue: <_i9.WorkExperiencesEntity>[],
        returnValueForMissingStub: <_i9.WorkExperiencesEntity>[],
      ) as List<_i9.WorkExperiencesEntity>);

  @override
  List<_i10.EducationsEntity> get educationsEntityList => (super.noSuchMethod(
        Invocation.getter(#educationsEntityList),
        returnValue: <_i10.EducationsEntity>[],
        returnValueForMissingStub: <_i10.EducationsEntity>[],
      ) as List<_i10.EducationsEntity>);

  @override
  List<_i11.LanguagesEntity> get languagesEntityList => (super.noSuchMethod(
        Invocation.getter(#languagesEntityList),
        returnValue: <_i11.LanguagesEntity>[],
        returnValueForMissingStub: <_i11.LanguagesEntity>[],
      ) as List<_i11.LanguagesEntity>);

  @override
  List<_i12.DrivingLicenseEntity> get drivingLicenseEntityList =>
      (super.noSuchMethod(
        Invocation.getter(#drivingLicenseEntityList),
        returnValue: <_i12.DrivingLicenseEntity>[],
        returnValueForMissingStub: <_i12.DrivingLicenseEntity>[],
      ) as List<_i12.DrivingLicenseEntity>);

  @override
  List<_i13.SkillsAndCompetencesEntity> get skillsAndCompetencesEntityList =>
      (super.noSuchMethod(
        Invocation.getter(#skillsAndCompetencesEntityList),
        returnValue: <_i13.SkillsAndCompetencesEntity>[],
        returnValueForMissingStub: <_i13.SkillsAndCompetencesEntity>[],
      ) as List<_i13.SkillsAndCompetencesEntity>);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
