// Mocks generated by Mockito 5.4.4 from annotations
// in aorlando/test/feature/home/vertical_divider_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i4;

import 'package:flutter/animation.dart' as _i9;
import 'package:flutter/foundation.dart' as _i3;
import 'package:flutter/gestures.dart' as _i7;
import 'package:flutter/rendering.dart' as _i5;
import 'package:flutter/src/widgets/framework.dart' as _i2;
import 'package:flutter/src/widgets/notification_listener.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWidget_0 extends _i1.SmartFake implements _i2.Widget {
  _FakeWidget_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeInheritedWidget_1 extends _i1.SmartFake
    implements _i2.InheritedWidget {
  _FakeInheritedWidget_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeDiagnosticsNode_2 extends _i1.SmartFake
    implements _i3.DiagnosticsNode {
  _FakeDiagnosticsNode_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({
    _i3.TextTreeConfiguration? parentConfiguration,
    _i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info,
  }) =>
      super.toString();
}

class _FakeSize_3 extends _i1.SmartFake implements _i4.Size {
  _FakeSize_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRect_4 extends _i1.SmartFake implements _i4.Rect {
  _FakeRect_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBoxConstraints_5 extends _i1.SmartFake
    implements _i5.BoxConstraints {
  _FakeBoxConstraints_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOffset_6 extends _i1.SmartFake implements _i4.Offset {
  _FakeOffset_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOffsetLayer_7 extends _i1.SmartFake implements _i5.OffsetLayer {
  _FakeOffsetLayer_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeMatrix4_8 extends _i1.SmartFake implements _i5.Matrix4 {
  _FakeMatrix4_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GlobalKey].
///
/// See the documentation for Mockito's code generation for more information.
class MockGlobalKey<T extends _i2.State<_i2.StatefulWidget>> extends _i1.Mock
    implements _i2.GlobalKey<T> {}

/// A class which mocks [BuildContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockBuildContext extends _i1.Mock implements _i2.BuildContext {
  @override
  _i2.Widget get widget => (super.noSuchMethod(
        Invocation.getter(#widget),
        returnValue: _FakeWidget_0(
          this,
          Invocation.getter(#widget),
        ),
        returnValueForMissingStub: _FakeWidget_0(
          this,
          Invocation.getter(#widget),
        ),
      ) as _i2.Widget);

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get debugDoingBuild => (super.noSuchMethod(
        Invocation.getter(#debugDoingBuild),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.InheritedWidget dependOnInheritedElement(
    _i2.InheritedElement? ancestor, {
    Object? aspect,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #dependOnInheritedElement,
          [ancestor],
          {#aspect: aspect},
        ),
        returnValue: _FakeInheritedWidget_1(
          this,
          Invocation.method(
            #dependOnInheritedElement,
            [ancestor],
            {#aspect: aspect},
          ),
        ),
        returnValueForMissingStub: _FakeInheritedWidget_1(
          this,
          Invocation.method(
            #dependOnInheritedElement,
            [ancestor],
            {#aspect: aspect},
          ),
        ),
      ) as _i2.InheritedWidget);

  @override
  void visitAncestorElements(_i2.ConditionalElementVisitor? visitor) =>
      super.noSuchMethod(
        Invocation.method(
          #visitAncestorElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void visitChildElements(_i2.ElementVisitor? visitor) => super.noSuchMethod(
        Invocation.method(
          #visitChildElements,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispatchNotification(_i6.Notification? notification) =>
      super.noSuchMethod(
        Invocation.method(
          #dispatchNotification,
          [notification],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.DiagnosticsNode describeElement(
    String? name, {
    _i3.DiagnosticsTreeStyle? style = _i3.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeElement,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeElement,
            [name],
            {#style: style},
          ),
        ),
        returnValueForMissingStub: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeElement,
            [name],
            {#style: style},
          ),
        ),
      ) as _i3.DiagnosticsNode);

  @override
  _i3.DiagnosticsNode describeWidget(
    String? name, {
    _i3.DiagnosticsTreeStyle? style = _i3.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeWidget,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeWidget,
            [name],
            {#style: style},
          ),
        ),
        returnValueForMissingStub: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeWidget,
            [name],
            {#style: style},
          ),
        ),
      ) as _i3.DiagnosticsNode);

  @override
  List<_i3.DiagnosticsNode> describeMissingAncestor(
          {required Type? expectedAncestorType}) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeMissingAncestor,
          [],
          {#expectedAncestorType: expectedAncestorType},
        ),
        returnValue: <_i3.DiagnosticsNode>[],
        returnValueForMissingStub: <_i3.DiagnosticsNode>[],
      ) as List<_i3.DiagnosticsNode>);

  @override
  _i3.DiagnosticsNode describeOwnershipChain(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeOwnershipChain,
          [name],
        ),
        returnValue: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeOwnershipChain,
            [name],
          ),
        ),
        returnValueForMissingStub: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeOwnershipChain,
            [name],
          ),
        ),
      ) as _i3.DiagnosticsNode);
}

/// A class which mocks [RenderBox].
///
/// See the documentation for Mockito's code generation for more information.
class MockRenderBox extends _i1.Mock implements _i5.RenderBox {
  @override
  bool get hasSize => (super.noSuchMethod(
        Invocation.getter(#hasSize),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Size get size => (super.noSuchMethod(
        Invocation.getter(#size),
        returnValue: _FakeSize_3(
          this,
          Invocation.getter(#size),
        ),
        returnValueForMissingStub: _FakeSize_3(
          this,
          Invocation.getter(#size),
        ),
      ) as _i4.Size);

  @override
  set size(_i4.Size? value) => super.noSuchMethod(
        Invocation.setter(
          #size,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Rect get semanticBounds => (super.noSuchMethod(
        Invocation.getter(#semanticBounds),
        returnValue: _FakeRect_4(
          this,
          Invocation.getter(#semanticBounds),
        ),
        returnValueForMissingStub: _FakeRect_4(
          this,
          Invocation.getter(#semanticBounds),
        ),
      ) as _i4.Rect);

  @override
  _i5.BoxConstraints get constraints => (super.noSuchMethod(
        Invocation.getter(#constraints),
        returnValue: _FakeBoxConstraints_5(
          this,
          Invocation.getter(#constraints),
        ),
        returnValueForMissingStub: _FakeBoxConstraints_5(
          this,
          Invocation.getter(#constraints),
        ),
      ) as _i5.BoxConstraints);

  @override
  _i4.Rect get paintBounds => (super.noSuchMethod(
        Invocation.getter(#paintBounds),
        returnValue: _FakeRect_4(
          this,
          Invocation.getter(#paintBounds),
        ),
        returnValueForMissingStub: _FakeRect_4(
          this,
          Invocation.getter(#paintBounds),
        ),
      ) as _i4.Rect);

  @override
  set parentData(_i5.ParentData? _parentData) => super.noSuchMethod(
        Invocation.setter(
          #parentData,
          _parentData,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set debugCreator(Object? _debugCreator) => super.noSuchMethod(
        Invocation.setter(
          #debugCreator,
          _debugCreator,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get depth => (super.noSuchMethod(
        Invocation.getter(#depth),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool get debugDoingThisResize => (super.noSuchMethod(
        Invocation.getter(#debugDoingThisResize),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get debugDoingThisLayout => (super.noSuchMethod(
        Invocation.getter(#debugDoingThisLayout),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get debugCanParentUseSize => (super.noSuchMethod(
        Invocation.getter(#debugCanParentUseSize),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get attached => (super.noSuchMethod(
        Invocation.getter(#attached),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get debugNeedsLayout => (super.noSuchMethod(
        Invocation.getter(#debugNeedsLayout),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get debugDoingThisLayoutWithCallback => (super.noSuchMethod(
        Invocation.getter(#debugDoingThisLayoutWithCallback),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get sizedByParent => (super.noSuchMethod(
        Invocation.getter(#sizedByParent),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get debugDoingThisPaint => (super.noSuchMethod(
        Invocation.getter(#debugDoingThisPaint),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isRepaintBoundary => (super.noSuchMethod(
        Invocation.getter(#isRepaintBoundary),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get alwaysNeedsCompositing => (super.noSuchMethod(
        Invocation.getter(#alwaysNeedsCompositing),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set layer(_i5.ContainerLayer? newLayer) => super.noSuchMethod(
        Invocation.setter(
          #layer,
          newLayer,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get needsCompositing => (super.noSuchMethod(
        Invocation.getter(#needsCompositing),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get debugNeedsPaint => (super.noSuchMethod(
        Invocation.getter(#debugNeedsPaint),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get debugNeedsCompositedLayerUpdate => (super.noSuchMethod(
        Invocation.getter(#debugNeedsCompositedLayerUpdate),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void setupParentData(_i5.RenderObject? child) => super.noSuchMethod(
        Invocation.method(
          #setupParentData,
          [child],
        ),
        returnValueForMissingStub: null,
      );

  @override
  double getMinIntrinsicWidth(double? height) => (super.noSuchMethod(
        Invocation.method(
          #getMinIntrinsicWidth,
          [height],
        ),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double computeMinIntrinsicWidth(double? height) => (super.noSuchMethod(
        Invocation.method(
          #computeMinIntrinsicWidth,
          [height],
        ),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double getMaxIntrinsicWidth(double? height) => (super.noSuchMethod(
        Invocation.method(
          #getMaxIntrinsicWidth,
          [height],
        ),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double computeMaxIntrinsicWidth(double? height) => (super.noSuchMethod(
        Invocation.method(
          #computeMaxIntrinsicWidth,
          [height],
        ),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double getMinIntrinsicHeight(double? width) => (super.noSuchMethod(
        Invocation.method(
          #getMinIntrinsicHeight,
          [width],
        ),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double computeMinIntrinsicHeight(double? width) => (super.noSuchMethod(
        Invocation.method(
          #computeMinIntrinsicHeight,
          [width],
        ),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double getMaxIntrinsicHeight(double? width) => (super.noSuchMethod(
        Invocation.method(
          #getMaxIntrinsicHeight,
          [width],
        ),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double computeMaxIntrinsicHeight(double? width) => (super.noSuchMethod(
        Invocation.method(
          #computeMaxIntrinsicHeight,
          [width],
        ),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  _i4.Size getDryLayout(_i5.BoxConstraints? constraints) => (super.noSuchMethod(
        Invocation.method(
          #getDryLayout,
          [constraints],
        ),
        returnValue: _FakeSize_3(
          this,
          Invocation.method(
            #getDryLayout,
            [constraints],
          ),
        ),
        returnValueForMissingStub: _FakeSize_3(
          this,
          Invocation.method(
            #getDryLayout,
            [constraints],
          ),
        ),
      ) as _i4.Size);

  @override
  _i4.Size computeDryLayout(_i5.BoxConstraints? constraints) =>
      (super.noSuchMethod(
        Invocation.method(
          #computeDryLayout,
          [constraints],
        ),
        returnValue: _FakeSize_3(
          this,
          Invocation.method(
            #computeDryLayout,
            [constraints],
          ),
        ),
        returnValueForMissingStub: _FakeSize_3(
          this,
          Invocation.method(
            #computeDryLayout,
            [constraints],
          ),
        ),
      ) as _i4.Size);

  @override
  bool debugCannotComputeDryLayout({
    String? reason,
    _i3.FlutterError? error,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #debugCannotComputeDryLayout,
          [],
          {
            #reason: reason,
            #error: error,
          },
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Size debugAdoptSize(_i4.Size? value) => (super.noSuchMethod(
        Invocation.method(
          #debugAdoptSize,
          [value],
        ),
        returnValue: _FakeSize_3(
          this,
          Invocation.method(
            #debugAdoptSize,
            [value],
          ),
        ),
        returnValueForMissingStub: _FakeSize_3(
          this,
          Invocation.method(
            #debugAdoptSize,
            [value],
          ),
        ),
      ) as _i4.Size);

  @override
  void debugResetSize() => super.noSuchMethod(
        Invocation.method(
          #debugResetSize,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  double? getDistanceToBaseline(
    _i4.TextBaseline? baseline, {
    bool? onlyReal = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDistanceToBaseline,
          [baseline],
          {#onlyReal: onlyReal},
        ),
        returnValueForMissingStub: null,
      ) as double?);

  @override
  double? getDistanceToActualBaseline(_i4.TextBaseline? baseline) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDistanceToActualBaseline,
          [baseline],
        ),
        returnValueForMissingStub: null,
      ) as double?);

  @override
  double? computeDistanceToActualBaseline(_i4.TextBaseline? baseline) =>
      (super.noSuchMethod(
        Invocation.method(
          #computeDistanceToActualBaseline,
          [baseline],
        ),
        returnValueForMissingStub: null,
      ) as double?);

  @override
  void debugAssertDoesMeetConstraints() => super.noSuchMethod(
        Invocation.method(
          #debugAssertDoesMeetConstraints,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void markNeedsLayout() => super.noSuchMethod(
        Invocation.method(
          #markNeedsLayout,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void layout(
    _i5.Constraints? constraints, {
    bool? parentUsesSize = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #layout,
          [constraints],
          {#parentUsesSize: parentUsesSize},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void performResize() => super.noSuchMethod(
        Invocation.method(
          #performResize,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void performLayout() => super.noSuchMethod(
        Invocation.method(
          #performLayout,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool hitTest(
    _i5.BoxHitTestResult? result, {
    required _i4.Offset? position,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #hitTest,
          [result],
          {#position: position},
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool hitTestSelf(_i4.Offset? position) => (super.noSuchMethod(
        Invocation.method(
          #hitTestSelf,
          [position],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool hitTestChildren(
    _i5.BoxHitTestResult? result, {
    required _i4.Offset? position,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #hitTestChildren,
          [result],
          {#position: position},
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void applyPaintTransform(
    _i5.RenderObject? child,
    _i5.Matrix4? transform,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #applyPaintTransform,
          [
            child,
            transform,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Offset globalToLocal(
    _i4.Offset? point, {
    _i5.RenderObject? ancestor,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #globalToLocal,
          [point],
          {#ancestor: ancestor},
        ),
        returnValue: _FakeOffset_6(
          this,
          Invocation.method(
            #globalToLocal,
            [point],
            {#ancestor: ancestor},
          ),
        ),
        returnValueForMissingStub: _FakeOffset_6(
          this,
          Invocation.method(
            #globalToLocal,
            [point],
            {#ancestor: ancestor},
          ),
        ),
      ) as _i4.Offset);

  @override
  _i4.Offset localToGlobal(
    _i4.Offset? point, {
    _i5.RenderObject? ancestor,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #localToGlobal,
          [point],
          {#ancestor: ancestor},
        ),
        returnValue: _FakeOffset_6(
          this,
          Invocation.method(
            #localToGlobal,
            [point],
            {#ancestor: ancestor},
          ),
        ),
        returnValueForMissingStub: _FakeOffset_6(
          this,
          Invocation.method(
            #localToGlobal,
            [point],
            {#ancestor: ancestor},
          ),
        ),
      ) as _i4.Offset);

  @override
  void handleEvent(
    _i5.PointerEvent? event,
    _i5.HitTestEntry<_i7.HitTestTarget>? entry,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #handleEvent,
          [
            event,
            entry,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool debugHandleEvent(
    _i5.PointerEvent? event,
    _i5.HitTestEntry<_i7.HitTestTarget>? entry,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #debugHandleEvent,
          [
            event,
            entry,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void debugPaint(
    _i5.PaintingContext? context,
    _i4.Offset? offset,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #debugPaint,
          [
            context,
            offset,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void debugPaintSize(
    _i5.PaintingContext? context,
    _i4.Offset? offset,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #debugPaintSize,
          [
            context,
            offset,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void debugPaintBaselines(
    _i5.PaintingContext? context,
    _i4.Offset? offset,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #debugPaintBaselines,
          [
            context,
            offset,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void debugPaintPointers(
    _i5.PaintingContext? context,
    _i4.Offset? offset,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #debugPaintPointers,
          [
            context,
            offset,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void debugFillProperties(_i3.DiagnosticPropertiesBuilder? properties) =>
      super.noSuchMethod(
        Invocation.method(
          #debugFillProperties,
          [properties],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reassemble() => super.noSuchMethod(
        Invocation.method(
          #reassemble,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void redepthChild(_i5.RenderObject? child) => super.noSuchMethod(
        Invocation.method(
          #redepthChild,
          [child],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void redepthChildren() => super.noSuchMethod(
        Invocation.method(
          #redepthChildren,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void adoptChild(_i5.RenderObject? child) => super.noSuchMethod(
        Invocation.method(
          #adoptChild,
          [child],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dropChild(_i5.RenderObject? child) => super.noSuchMethod(
        Invocation.method(
          #dropChild,
          [child],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void visitChildren(_i5.RenderObjectVisitor? visitor) => super.noSuchMethod(
        Invocation.method(
          #visitChildren,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void attach(_i5.PipelineOwner? owner) => super.noSuchMethod(
        Invocation.method(
          #attach,
          [owner],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void detach() => super.noSuchMethod(
        Invocation.method(
          #detach,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void markParentNeedsLayout() => super.noSuchMethod(
        Invocation.method(
          #markParentNeedsLayout,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void markNeedsLayoutForSizedByParentChange() => super.noSuchMethod(
        Invocation.method(
          #markNeedsLayoutForSizedByParentChange,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void scheduleInitialLayout() => super.noSuchMethod(
        Invocation.method(
          #scheduleInitialLayout,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void invokeLayoutCallback<T extends _i5.Constraints>(
          _i5.LayoutCallback<T>? callback) =>
      super.noSuchMethod(
        Invocation.method(
          #invokeLayoutCallback,
          [callback],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void debugRegisterRepaintBoundaryPaint({
    bool? includedParent = true,
    bool? includedChild = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #debugRegisterRepaintBoundaryPaint,
          [],
          {
            #includedParent: includedParent,
            #includedChild: includedChild,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.OffsetLayer updateCompositedLayer({required _i5.OffsetLayer? oldLayer}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCompositedLayer,
          [],
          {#oldLayer: oldLayer},
        ),
        returnValue: _FakeOffsetLayer_7(
          this,
          Invocation.method(
            #updateCompositedLayer,
            [],
            {#oldLayer: oldLayer},
          ),
        ),
        returnValueForMissingStub: _FakeOffsetLayer_7(
          this,
          Invocation.method(
            #updateCompositedLayer,
            [],
            {#oldLayer: oldLayer},
          ),
        ),
      ) as _i5.OffsetLayer);

  @override
  void markNeedsCompositingBitsUpdate() => super.noSuchMethod(
        Invocation.method(
          #markNeedsCompositingBitsUpdate,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void markNeedsPaint() => super.noSuchMethod(
        Invocation.method(
          #markNeedsPaint,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void markNeedsCompositedLayerUpdate() => super.noSuchMethod(
        Invocation.method(
          #markNeedsCompositedLayerUpdate,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void scheduleInitialPaint(_i5.ContainerLayer? rootLayer) =>
      super.noSuchMethod(
        Invocation.method(
          #scheduleInitialPaint,
          [rootLayer],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void replaceRootLayer(_i5.OffsetLayer? rootLayer) => super.noSuchMethod(
        Invocation.method(
          #replaceRootLayer,
          [rootLayer],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void paint(
    _i5.PaintingContext? context,
    _i4.Offset? offset,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #paint,
          [
            context,
            offset,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool paintsChild(_i5.RenderObject? child) => (super.noSuchMethod(
        Invocation.method(
          #paintsChild,
          [child],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Matrix4 getTransformTo(_i5.RenderObject? ancestor) => (super.noSuchMethod(
        Invocation.method(
          #getTransformTo,
          [ancestor],
        ),
        returnValue: _FakeMatrix4_8(
          this,
          Invocation.method(
            #getTransformTo,
            [ancestor],
          ),
        ),
        returnValueForMissingStub: _FakeMatrix4_8(
          this,
          Invocation.method(
            #getTransformTo,
            [ancestor],
          ),
        ),
      ) as _i5.Matrix4);

  @override
  _i4.Rect? describeApproximatePaintClip(_i5.RenderObject? child) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeApproximatePaintClip,
          [child],
        ),
        returnValueForMissingStub: null,
      ) as _i4.Rect?);

  @override
  void scheduleInitialSemantics() => super.noSuchMethod(
        Invocation.method(
          #scheduleInitialSemantics,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void describeSemanticsConfiguration(_i5.SemanticsConfiguration? config) =>
      super.noSuchMethod(
        Invocation.method(
          #describeSemanticsConfiguration,
          [config],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sendSemanticsEvent(_i5.SemanticsEvent? semanticsEvent) =>
      super.noSuchMethod(
        Invocation.method(
          #sendSemanticsEvent,
          [semanticsEvent],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearSemantics() => super.noSuchMethod(
        Invocation.method(
          #clearSemantics,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void markNeedsSemanticsUpdate() => super.noSuchMethod(
        Invocation.method(
          #markNeedsSemanticsUpdate,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void visitChildrenForSemantics(_i5.RenderObjectVisitor? visitor) =>
      super.noSuchMethod(
        Invocation.method(
          #visitChildrenForSemantics,
          [visitor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void assembleSemanticsNode(
    _i5.SemanticsNode? node,
    _i5.SemanticsConfiguration? config,
    Iterable<_i5.SemanticsNode>? children,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #assembleSemanticsNode,
          [
            node,
            config,
            children,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String toStringShort() => (super.noSuchMethod(
        Invocation.method(
          #toStringShort,
          [],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #toStringShort,
            [],
          ),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #toStringShort,
            [],
          ),
        ),
      ) as String);

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();

  @override
  String toStringDeep({
    String? prefixLineOne = r'',
    String? prefixOtherLines = r'',
    _i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.debug,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toStringDeep,
          [],
          {
            #prefixLineOne: prefixLineOne,
            #prefixOtherLines: prefixOtherLines,
            #minLevel: minLevel,
          },
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #toStringDeep,
            [],
            {
              #prefixLineOne: prefixLineOne,
              #prefixOtherLines: prefixOtherLines,
              #minLevel: minLevel,
            },
          ),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #toStringDeep,
            [],
            {
              #prefixLineOne: prefixLineOne,
              #prefixOtherLines: prefixOtherLines,
              #minLevel: minLevel,
            },
          ),
        ),
      ) as String);

  @override
  String toStringShallow({
    String? joiner = r', ',
    _i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.debug,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toStringShallow,
          [],
          {
            #joiner: joiner,
            #minLevel: minLevel,
          },
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #toStringShallow,
            [],
            {
              #joiner: joiner,
              #minLevel: minLevel,
            },
          ),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #toStringShallow,
            [],
            {
              #joiner: joiner,
              #minLevel: minLevel,
            },
          ),
        ),
      ) as String);

  @override
  List<_i3.DiagnosticsNode> debugDescribeChildren() => (super.noSuchMethod(
        Invocation.method(
          #debugDescribeChildren,
          [],
        ),
        returnValue: <_i3.DiagnosticsNode>[],
        returnValueForMissingStub: <_i3.DiagnosticsNode>[],
      ) as List<_i3.DiagnosticsNode>);

  @override
  void showOnScreen({
    _i5.RenderObject? descendant,
    _i4.Rect? rect,
    Duration? duration = Duration.zero,
    _i9.Curve? curve = _i9.Curves.ease,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #showOnScreen,
          [],
          {
            #descendant: descendant,
            #rect: rect,
            #duration: duration,
            #curve: curve,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.DiagnosticsNode describeForError(
    String? name, {
    _i3.DiagnosticsTreeStyle? style = _i3.DiagnosticsTreeStyle.shallow,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #describeForError,
          [name],
          {#style: style},
        ),
        returnValue: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeForError,
            [name],
            {#style: style},
          ),
        ),
        returnValueForMissingStub: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #describeForError,
            [name],
            {#style: style},
          ),
        ),
      ) as _i3.DiagnosticsNode);

  @override
  _i3.DiagnosticsNode toDiagnosticsNode({
    String? name,
    _i3.DiagnosticsTreeStyle? style,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toDiagnosticsNode,
          [],
          {
            #name: name,
            #style: style,
          },
        ),
        returnValue: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #toDiagnosticsNode,
            [],
            {
              #name: name,
              #style: style,
            },
          ),
        ),
        returnValueForMissingStub: _FakeDiagnosticsNode_2(
          this,
          Invocation.method(
            #toDiagnosticsNode,
            [],
            {
              #name: name,
              #style: style,
            },
          ),
        ),
      ) as _i3.DiagnosticsNode);
}
